name: CI/CD # 此工作流程（workflow）的名字
on:
  push: # 触发此文件运行的条件
    branches:
      - build-deploy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        run: npm i pnpm -g

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          echo "VITE_GITHUB_CLIENT_ID=${{ secrets.VITE_GITHUB_CLIENT_ID }}" >> $GITHUB_ENV
          echo "VITE_GITHUB_CLIENT_SECRET=${{ secrets.VITE_GITHUB_CLIENT_SECRET }}" >> $GITHUB_ENV

      - name: Install and Build
        run: |
          pnpm install
          pnpm build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: .vitepress/dist
